spring:
  mail:
    host: smtp.yandex.ru
    port: 587
    username: qwerty534534
    password: nnrtwtjypxqijtdv

  datasource:
    url: jdbc:h2:mem:mvc-demo-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console