server:
  port: 8086

spring:
  application:
    name: GymTracker

  config:
    import: classpath:config.properties

  profiles:
    active: prod

  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      encoding: UTF-8


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

