spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false

  datasource:
    url: jdbc:postgresql://localhost:5432/gymdb
    username: postgres
    password: zxcqwe

logging:
    level:
      root: DEBUG